//! Does joining the tonebar give the attack what the service literature says?
//!
//! The Chicago Electric Piano Co. describes the bark as "the overtones
//! generated by the Rhodes' tine and tone bar when proper escapement and
//! pickup distance is set to capture these overtones within their magnetic
//! fields". This model ships with `tonebar_coupling` at zero, so the second
//! prong is neither struck nor heard.
//!
//! It was left at zero because docs/PLAYABLE-TONEBAR.md found no improvement
//! on the frozen objective -- an objective that scores H2 to H4 over windows
//! far longer than the attack, and is blind to it. The same blind spot has
//! now been found twice.
//!
//! Renders a coupling sweep for measurement elsewhere. Promotes nothing.
//!
//! `cargo run --release -p rf-tines-lab --example tonebar_attack -- OUT_DIR`
#[allow(dead_code)]
#[path = "matts_fit.rs"]
mod previous;
use previous::{Result, baseline};
use rf_tines_dsp::{Engine, Profile};
use std::{fs, io::Write, path::Path};

const RATE: f64 = 48_000.0;
const NOTE: u8 = 52;

fn write_wav(path: &Path, samples: &[f64]) -> std::io::Result<()> {
    let bytes = (samples.len() * 4) as u32;
    let mut file = fs::File::create(path)?;
    file.write_all(b"RIFF")?;
    file.write_all(&(36 + bytes).to_le_bytes())?;
    file.write_all(b"WAVEfmt ")?;
    file.write_all(&16u32.to_le_bytes())?;
    file.write_all(&3u16.to_le_bytes())?;
    file.write_all(&1u16.to_le_bytes())?;
    file.write_all(&(RATE as u32).to_le_bytes())?;
    file.write_all(&((RATE as u32) * 4).to_le_bytes())?;
    file.write_all(&4u16.to_le_bytes())?;
    file.write_all(&32u16.to_le_bytes())?;
    file.write_all(b"data")?;
    file.write_all(&bytes.to_le_bytes())?;
    for value in samples {
        file.write_all(&(*value as f32).to_le_bytes())?;
    }
    Ok(())
}

fn main() -> Result<()> {
    let out = std::env::args()
        .nth(1)
        .ok_or("usage: tonebar_attack OUT_DIR")?;
    let out = Path::new(&out);
    fs::create_dir_all(out)?;
    for coupling in [4.0, 0.8, 0.25, 0.08, 0.03] {
        let profile = Profile {
            tonebar_clamp: 1.0,

            tonebar_decay_seconds: coupling,
            ..baseline()
        };
        let mut engine = Engine::new(RATE, profile)?;
        engine.set_gain(0.5);
        engine.set_level_compensation(true);
        engine.reset();
        engine.note_on(0, NOTE, 0.85);
        let signal: Vec<f64> = (0..(RATE * 3.0) as usize)
            .map(|_| f64::from(engine.next_sample()))
            .collect();
        write_wav(&out.join(format!("bar-{coupling:.1}.wav")), &signal)?;
        println!("union {coupling:.1} rendida");
    }
    Ok(())
}
